### ISSUE TITLE
Implementing Additional Ensemble Algorithms in the Project

### ISSUE THREAD

**Issue by carlosfrodrigues** [carlosfrodrigues/millesime#1]
Millésime was tested using only two ensemble algorithms - RandomForrestRegressor and Bagging. There are other algorithms we could explore for comparing performance. 
The file where the models are being tested is `app/services/python/generate_model.py`. In addition to the implementation, it would be interesting to have a graph showing the MSE and R2 score for each algorithm to validate our choice among the options.

**Comment by lucasortman** [comment]
Hi! Could you assign this for me?

**Comment by lucasortman** [comment]
Closed #2

**Comment by carlosfrodrigues** [comment]
Perfect!
