### ISSUE TITLE
Allowing More Precise Field Inputs in Millésime

### ISSUE THREAD

**Issue by carlosfrodrigues** [carlosfrodrigues/millesime#3]
**Issue Statement:**

Currently, Millésime restricts the precision of input values by allowing only two digits after the decimal point for every data entry. To ensure more accurate and refined predictions, the app should permit greater precision in certain inputs, taking cues from the `winequality-red.csv` dataset.

![image](https://github.com/carlosfrodrigues/millesime/assets/18339454/474843c2-441f-443c-813f-19585412b118)

**Proposed Solution:**

It's necessary to expand the input field for fields like density and chlorides to accommodate more than two digits after the decimal point. This modification would empower users to provide a more granular and precise measurement of field density, allowing the app's machine learning algorithms to better discern the quality variations among different wines.

**Comment by Selitek** [comment]
Hi,
can I work on this issue?
Thanks!

**Comment by carlosfrodrigues** [comment]
Perfect! You can take it

**Comment by Selitek** [comment]
Thanks! 
Just to make sure, is the proposed solution increasing the length dimension of the input fields?

**Comment by carlosfrodrigues** [comment]
@Selitek 
Maybe not in all cases will you need to increase the length dimension of the input field. You should check the winequality-red.csv file and decide which ones it would be a good idea to increase the number of digits after the decimal point. The density field is certainly one of those.

**Comment by Selitek** [comment]
Thank you for the elaboration. I will start working on it!
